version: '3.8'
services:
  suricata:
    build: ./suricata
    container_name: router_suricata
    privileged: true
    cap_add:
      - NET_ADMIN  # Necessario per gestire le interfacce di rete
    networks:
      web_net:
        ipv4_address: 172.18.0.2
      attack_net:
        ipv4_address: 172.19.0.2
    environment:
      - INTERFACES=eth0 eth1  
    ports:
      - "8000:8000"  # Esempio, se vuoi accedere ai log o statistiche via web

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      internal_net:
        ipv4_address: 10.0.0.4
      
  webserver:
    build: ./webserver
    container_name: webserver
    privileged: true
    networks:
      web_net:
        ipv4_address: 172.18.0.3
      internal_net:
        ipv4_address: 10.0.0.3
    depends_on:
      - suricata
    ports:
      - "8080:80"
    environment:
      - INTERFACES=eth0 eth1  
    cap_add:
    - NET_ADMIN 

  attacker:
    build: ./attacker
    container_name: attacker
    stdin_open: true   #container_name: attacker
    networks:
      attack_net:
        ipv4_address: 172.19.0.3
    cap_add:
      - NET_ADMIN
    tty: true  # Mantiene il container aperto per interazioni manuali
    depends_on:
      - suricata

networks:
  web_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
  attack_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
